### ISSUE TITLE
`keep list` output

### ISSUE THREAD

**Issue by HKLF4** [OrkoHunter/keep#15]
Output of `keep list` is unreadable when storing really long commands in keep (see screenshot, please). It’s good idea to use for it list with highlighting (like `git log`) but not table, I think.

![keep list](https://cloud.githubusercontent.com/assets/474168/23363645/c3399dc8-fd0c-11e6-917f-60956e0bed0e.png)

**Comment by OrkoHunter** [comment]
Yes, you are right. I could not find any good table printer in python with option to wrap the column.

**Comment by KarlFiabeschi** [comment]
maybe different color from title or command/desc can help

**Comment by iHarshad** [comment]
I just ran into this problem with long commands.

Hope this solves it -> http://stackoverflow.com/a/28817301

**Comment by athityakumar** [comment]
Hey @OrkoHunter! Saw keep after the demo day, and this seems quite awesome. So, I started to dig into the codebase trying to fix this with the help of `terminaltables` library (rather than `tabulate`). If the below screenshot looks better, I could send in a PR. 😄 

![image](https://user-images.githubusercontent.com/17109060/35748964-eeb27ff4-0875-11e8-96e5-80dd1c76e311.png)

**Comment by OrkoHunter** [comment]
@athityakumar Thank you for working on this! This looks perfect. :)

**Comment by athityakumar** [comment]
Great! Opened PR #40 - have a look! 😄

**Comment by OrkoHunter** [comment]
Closed in #40
